apiVersion: v1
kind: Service
metadata:
  name: price-generator
  labels:
    app: price-generator
spec:
  type: NodePort
  ports:
  - port : 8083
    protocol: TCP
    targetPort: 8083
    nodePort: 30083
  selector:
    app: price-generator